%classify all GSV images using caffe
clear all;

detected_bboxes_root='/home/jkrause/gsv_data/city_results_merged_cal/';
detected_files=dir(detected_bboxes_root);

%Go through cities by alphabetical order
city_mask=(1:numel(detected_files)).*...
    arrayfun(@(x)x.name(1) ~='.',detected_files)';
city_mask(find(city_mask==0))=[];
cities=arrayfun(@(x)x.name,detected_files(city_mask),'uniformoutput',false);
num_cities=numel(cities);

%breakup cities into batches
NUM_BATCHES=4;
batch_size=ceil(num_cities/NUM_BATCHES);

%start a process to run each batch in a particular gpu
batch_num=0;
batch_start=3*batch_size+1;
%{
for c=batch_start:batch_size: 4*batch_size%num_cities
  batch_num=batch_num+1;
  end_indx=min(c+batch_size-1,num_cities);
  city_queue=cities(c:end_indx);
  %city_queue={'worcester_massachusetts.mat','springfield_massachusetts.mat'};
  gsv_classify_all_gpu(3,city_queue,batch_num);
end
%}

city_queue={...
  'dallas_texas.mat',...
  'fort worth_texas.mat',...
  'pittsburgh_pennsylvania.mat',...
  'tucson_arizona.mat',...
  'santa clarita_california.mat',...
  'baltimore_maryland.mat',...
  'oklahoma city_oklahoma.mat',...
  'los angeles_california.mat',...
  'san antonio_texas.mat',...
  'chicago_illinois.mat',...
  'phoenix_arizona.mat',...
  'minneapolis_minnesota.mat'...

};
gsv_classify_all_gpu(3,city_queue,batch_num);
