%classify all GSV images using caffe
clear all;

detected_bboxes_root='/home/jkrause/gsv_data/city_results_merged_cal/';
detected_files=dir(detected_bboxes_root);


%Go through cities by alphabetical order
city_mask=(1:numel(detected_files)).*...
    arrayfun(@(x)x.name(1) ~='.',detected_files)';
city_mask(find(city_mask==0))=[];
cities=arrayfun(@(x)x.name,detected_files(city_mask),'uniformoutput',false);
num_cities=numel(cities);

%breakup cities into batches
NUM_BATCHES=4;
batch_size=ceil(num_cities/NUM_BATCHES);

%start a process to run each batch in a particular gpu
batch_num=0;
%for c=1: num_cities
  %batch_num=batch_num+1;
  %end_indx=min(c+batch_size-1,num_cities);
  %city_queue=cities(c:end_indx);
  
  %{
  city_queue={'aurora_colorado.mat', ...
        'garland_texas.mat',...
        'hayward_california.mat',...
        'irving_texas.mat',...
        'oklahoma city_oklahoma.mat',...
        'reno_nevada.mat',...
        'sacramento_california.mat',...
        'salinas_california.mat'}
  %} 
  %city_queue={'reno_nevada.mat'}
  city_queue={...
    'dallas_texas.mat',...
    'fort worth_texas.mat',...
    'pittsburgh_pennsylvania.mat',...
    'tucson_arizona.mat',...
    'santa clarita_california.mat',...
    'baltimore_maryland.mat',...
    'oklahoma city_oklahoma.mat',...
    'los angeles_california.mat',...
    'san antonio_texas.mat',...
    'chicago_illinois.mat',...
    'phoenix_arizona.mat',...
    'minneapolis_minnesota.mat'...
  
  };
  gsv_classify_all_gpu(2,city_queue,batch_num);
%end
